### ISSUE TITLE
mlat-client does not start at reboot

### ISSUE THREAD

**Issue by mgunther68** [mutability/mlat-client#11]
I find that mlat-client does not start at reboot and I see this in /var/log/mlat-client:

```
Wed Feb 10 20:41:07 2016 mlat-client 0.2.5~dev starting up
Wed Feb 10 20:41:07 2016 Listening for Basestation-format results connection on port 31003
Wed Feb 10 20:41:08 2016 Connection to server.mlat-radar.net:40147 failed: [Errno -3] Temporary failure in name resolution
Wed Feb 10 20:41:08 2016 Reconnecting in 30.0 seconds
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncore.py", line 411, in __getattr__
    retattr = getattr(self.socket, attr)
AttributeError: 'NoneType' object has no attribute 'reader'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mlat-client", line 101, in <module>
    main()
  File "/usr/bin/mlat-client", line 98, in main
    coordinator.run_forever()
  File "/usr/lib/python3/dist-packages/mlat/client/coordinator.py", line 90, in run_forever
    self.run_until(lambda: False)
  File "/usr/lib/python3/dist-packages/mlat/client/coordinator.py", line 106, in run_until
    self.heartbeat(now)
  File "/usr/lib/python3/dist-packages/mlat/client/coordinator.py", line 126, in heartbeat
    self.update_aircraft(now)
  File "/usr/lib/python3/dist-packages/mlat/client/coordinator.py", line 143, in update_aircraft
    for icao in self.receiver.recent_aircraft():
  File "/usr/lib/python3/dist-packages/mlat/client/receiver.py", line 127, in recent_aircraft
    recent = set(self.reader.seen)
  File "/usr/lib/python3.4/asyncore.py", line 414, in __getattr__
    %(self.__class__.__name__, attr))
AttributeError: ReceiverConnection instance has no attribute 'reader'
```

Trying to manually start it appears to be successful:

```
pi@raspberrypi:~ $ sudo /etc/init.d/mlat-client start
[ ok ] Starting mlat-client (via systemctl): mlat-client.service.
```

However, nothing is written to the log file and no mlat-client process is present in ps -ef

**Comment by mgunther68** [comment]
And to add, ping works fine later:

```
pi@raspberrypi:~ $ sudo ping server.mlat-radar.net
PING server.mlat-radar.net (151.80.116.49) 56(84) bytes of data.
64 bytes from 49.ip-151-80-116.eu (151.80.116.49): icmp_seq=1 ttl=49 time=29.5 ms
```

**Comment by mgunther68** [comment]
After another reboot and a few manual start attempts I see this:

```
pi@raspberrypi:~ $ sudo /etc/init.d/mlat-client status
● mlat-client.service - LSB: Multilateration client
   Loaded: loaded (/etc/init.d/mlat-client)
   Active: active (exited) since Wed 2016-02-10 20:58:55 GMT; 16min ago
  Process: 330 ExecStart=/etc/init.d/mlat-client start (code=exited, status=0/SUCCESS)

Feb 10 20:58:55 raspberrypi systemd[1]: Started LSB: Multilateration client.
Feb 10 21:10:07 raspberrypi systemd[1]: Started LSB: Multilateration client.
Feb 10 21:15:47 raspberrypi systemd[1]: Started LSB: Multilateration client.
```

Status is Loaded but Exited... 

A restart DOES work:

```
pi@raspberrypi:~ $ sudo /etc/init.d/mlat-client restart
[ ok ] Restarting mlat-client (via systemctl): mlat-client.service.
pi@raspberrypi:~ $ sudo /etc/init.d/mlat-client status
● mlat-client.service - LSB: Multilateration client
   Loaded: loaded (/etc/init.d/mlat-client)
   Active: active (running) since Wed 2016-02-10 21:18:16 GMT; 3s ago
  Process: 1700 ExecStop=/etc/init.d/mlat-client stop (code=exited, status=0/SUCCESS)
  Process: 1711 ExecStart=/etc/init.d/mlat-client start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/mlat-client.service
           └─1721 /usr/bin/python3.4 /usr/bin/mlat-client --user Cahersiveen --lat xx.xxxx --lon yy.yyyy --alt 22 --input-type dump1090 --i...

Feb 10 21:18:16 raspberrypi systemd[1]: Started LSB: Multilateration client.
```

**Comment by mutability** [comment]
This is using HEAD, I guess?

**Comment by mgunther68** [comment]
Thanks, tested and working now:)
