### ISSUE TITLE
Receiver microADSB

### ISSUE THREAD

**Issue by Chrisoo** [mutability/mlat-client#12]
Do you know when you will be supported receiver microADSB?

**Comment by mutability** [comment]
If it can produce Beast-format output with a stable clock, it's already supported.

Otherwise, what output format does it produce?

**Comment by Chrisoo** [comment]
> @0000B9891038BF763C4003C220A814218189FDAA;
> @0000B9A133D0ED42BD27910BA968908378C8C0B1;
> @0000BA71D290FBC0BB8F51813101282853919C17;
> @0000BAC8C3D8FD3E3850E681F43AE55999F45150;
> @0000BC4E15E0FF537B3DE8A13AB6AB0F0C1BCE8A;
> @0000BCDC2FE0165025A4404006;
> @0000BCF0DA28B2C4D81577932562CB0CABF19A18;
> @0000BDA81AD8DFC2E2488D9E05FD645635068273;
> @0000BFB22C60FA403784C8AC1D2C61471800FACF;
> @0000BFDE459002E198385F1FD7;
> @0000BFFE0650DCE93418F1C29C8DCA0201D838D2;
> @0000C0169750FE6E41568840A0A7C580E1A0A8DE;
> @0000C01EF9E08D4844C669C383FD3C3BCE75493D;
> @0000CBCEB0205D48AD0001BEE5;
> @0000CBD523705D48AD0001BEE4;
> @0000CBD8D8502000171802A36B;
> @0000CBDA5FC0280001B99F7B83;
> @0000CBDB40685D48AD0001BEE4;
> @0000CBDBE710280001B99F7B83;
> @0000CBE15D305D48AD0001BEE4;
> @0000CD2840102000171802A36B;
> @0000CD2FD4505D48AD0001BEE5;
> @0000CD9789405D471F858D6CF8;
> @0000CD9BC20002E617192C004E;
> @0000CDA2C758A8000311DBBA0730E01401C6B993;
> @0000CDABCC708D471F8560B99753401AC565D0CD;
> @0000CDB491C85D471F858D6CF8;
> @0000CDC2D89820001719F2E5E7;
> @0000CDD267C85D471F858D6CF9;
> @0000CDD576405D471F858D6CF9;
> @0000CDDFD558A0001719205DA6B4E7082085A6E8;
> @0000CDE0BE30A8000311C650002FC800004705D9;
> @0000CDE1AA78A0001719FFFBC5347FFCE3F9AB81;
> @0000CDE37E6020001719F2E5E7;
> @0000CDE92090A8000311C650002FC800004705D9;
> @0000CDEA2198A0001719FFFBC5347FFCE3F9AB81;
> @0000CDEB23E0A0001719DBAA0530FFFFFF071FA2;
> @0000CDEC259020001719F2E5E7;
> @0000CDEC0E90A8000311DBAA0530FFFFFF23F08E;
> @0000CDF917788D471F859945A1850804B8D0D958;
> @0000CDFFEC508D471F8560B993EC503882277593;
> @0000CE07EA488D471F859945A1850804B8D0D958;
> @0000CE0F27C85D471F858D6CF8;
> @0000CE183418A0001719C650002FC8000063EAF5;
> @0000CE191810280003118A651A;
> @0000CE1A0870A8000311FFFBC5347FFCE3DD44AD;
> @0000CE1AF378A0001719DBAA0730E027FE7919DE;
> @0000CE1BDB3820001719F2E5E7;
> @0000CE29F828A0001719C650002FC8000063EAF5;
> @0000CE2C47B0A8000311DBAA0730E017FE836AFB;
> @0000CE3BA4A88D471F859945A1850808B8988358;
> @0000CE40E248A8000311FFFBC5346004E364E74D;
> @0000CE42E02820001719F2E5E7;
> @0000CE4C4AC05D471F858D6CF8;
> @0000CE4CEE38A0001719C650002FC8000063EAF5;
> @0000CE4F3CE0A8000311DBAA0730FFD7FE943912;
> @0000CE53FA0802E617192C004E;
> @0000CE53F2588D471F859945A1850808B9677751;
> @0000CE5BBBA88D471F8560B993EC3037D4B1FAFD;
> @0000CE6550908D471F8560B99752E218D219D664;
> @0000CE668FC88D471F859945A1850808B8988358;
> @0000CE67F8285D471F858D6CF8;
> @0000CE6984A0A8000311801BC5346004E4476DD6;
> @0000CE6A6F58A0001719DBAA07313FD7FEFBD792;
> @0000CE6B57B820001719F2E5E7;
> @0000CE75E47802E617192C004E;
> @0000CE81F7288D471F859945A1850808B8988358;
> @0000CE8802A88D471F85205DA6B4E708205B8CB2;
> @0000CE961C608D471F8560B99752D2187978B153;
> @0000CE9B67A85D471F858D6CF8;
> @0000CE9D4B708D471F859945A1850808B9677751;
> @0000CEA2BC10A0001719C650002FC8000063EAF5;
> @0000CEA50A70A8000311DBAA09312057FF597F98;
> @0000CEAFEE108D471F8560B99752CC1859E66F7D;
> @0000CEB01C00A0001719205DA6B4E7082085A6E8;
> @0000CEB21DE8A0001719803BC3346004E4CDCA87;
> @0000CEB420D820001719F2E5E7;
> @0000CEB5B0F8A0001719C650002FC8000063EAF5;
> @0000CEB7FFA8A8000311DBAA0931200FFFB5438A;
> @0000CEBCD6A88D471F859945A1850804B8D0D958;
> @0000CEBEA008280003118A651A;
> @0000CEBF4A585D471F858D6CF9;
> @0000CEBFF0B8280003118A651A;
> @0000CEC48618280003118A651A;
> @0000CEC566B85D471F858D6CF9;
> @0000CEC874E85D471F858D6CF9;
> @0000CED312988D471F859945A1850804B92F2D51;
> @0000CF3ADE70A8000311C650002FC800004705D9;
> @0000CF3BC850A0001719801BC5342004E2E95E85;
> @0000CF41D9B05D471F858D6CF9;
> @0000CF443C48280003118A651A;
> @0000CF4714F8280003118A651A;
> @0000CF489BF0280003118A651A;
> @0000CF4A22B0280003118A651A;
> @0000CF4E12305D471F858D6CF9;
> @0000CF53AD18A8000311DBAA0530FFC7FE72F48E;
> @0000CF577A785D471F858D6CF8;
> @0000CF5E3C18A0001718C650002FC800001D30D7;
> @0000CF5F4880A8000311803BC5342004E269C770;
> @0000CF605308A0001718DBAA0530FFD7FEC81980;
> @0000CF616028200017180D11EE;
> @0000CF6AD8C002E197180BC9A4;
> @0000CF7368F88D471F8560B983EB4A330DF6B958;
> @0000CF7C85205D471F858D6CF8;
> @0000CF83152802E19719F43DAD;
> @0000CF83A63802E19719F43DAD;
> @0000CF8BDB185D471F858D6CF8;
> @0000CF91A83002E197180BC9A4;
> @0000CF929788A0001718C650002FC800001D30D7;
> @0000CF9E63E8A0001718DBBA0530E007FE925301;
> @0000CF9F69B8200017180D11EE;
> @0000CFA726805D471F858D6CF8;
> @0000CFAEFBF08D471F8560B98751F213D51593C5;
> @0000CFB6A2E0A0001718205DA6B4E70820FB7CCA;
> @0000CFB8BD08A0001718809BC5342014E3196FD1;
> @0000CFBBBA688D471F8560B983EB2A325F344F00;
> @0000CFC0DE2802E61718D3F447;
> @0000CFC0C6405D471F858D6CF8;
> @0000CFCD3DE88D471F8560B98751E21385CBB46D;
> @0000CFD64828A8000311807BC7343FFCE26168B7;
> @0000CFDE6298200017180D11EE;
> @0000CFE75018A8000311809BC734200CE22A0F4A;
> @0000D3FB5AE8B901008000000008140800000000;

This is a quote from the instruction decoder:

> If the bit 4 of the mode-byte is set to 1, then the decoder will add time stamps to all
> frames. These time stamps are required for MLAT. The time stamp is a 48-bit counter
> that increments with 12-MHz clock. It is used as prefix to the raw-data at each frame.
> If the time counter is active, then instead of the leading ’*’ a ‘@’ is used as prefix of
> the string.
> @123456789ABC12345678901234;
> @123456789ABC1234567890123456789012345678;

**Comment by mutability** [comment]
master HEAD already supports that, try a receiver type of "auto" or "avrmlat" and let me know if it works OK

**Comment by Chrisoo** [comment]
The same is to "auto" and "avrmlat":

> Sat Feb 13 21:43:14 2016 Connected to multilateration server at localhost:33031, handshaking
> Sat Feb 13 21:43:14 2016 Lost connection to localhost:33031
> Sat Feb 13 21:43:14 2016 Reconnecting in 30.0 seconds
> Sat Feb 13 21:43:44 2016 Connected to multilateration server at localhost:33031, handshaking
> Sat Feb 13 21:43:44 2016 Lost connection to localhost:33031
> Sat Feb 13 21:43:44 2016 Reconnecting in 30.0 seconds
> Sat Feb 13 21:44:14 2016 Connected to multilateration server at localhost:33031, handshaking
> Sat Feb 13 21:44:14 2016 Lost connection to localhost:33031
> Sat Feb 13 21:44:14 2016 Reconnecting in 30.0 seconds
> Sat Feb 13 21:44:44 2016 Connected to multilateration server at localhost:33031, handshaking
> Sat Feb 13 21:44:44 2016 Lost connection to localhost:33031
> Sat Feb 13 21:44:44 2016 Reconnecting in 30.0 seconds

The mlat-server shows up something like this:

> 20160213 21:49:29.092  INFO     client               [127.0.0.1:42402] Accepted new client connection
> 20160213 21:49:29.093  ERROR    client               [127.0.0.1:42402] Exception handling client
> Traceback (most recent call last):
>   File "/home/mlat-server/mlat/server/jsonclient.py", line 278, in handle_connection
>     if not self.process_handshake(hs):
>   File "/home/mlat-server/mlat/server/jsonclient.py", line 367, in process_handshake
>     connection_info=conn_info)
>   File "/home/mlat-server/mlat/server/coordinator.py", line 267, in new_receiver
>     clock = clocksync.make_clock(clock_type)
>   File "/home/mlat-server/mlat/server/clocksync.py", line 63, in make_clock
>     raise NotImplementedError
> NotImplementedError
> 20160213 21:49:29.093  INFO     client               [127.0.0.1:42402] Disconnected

**Comment by mutability** [comment]
OK, that's because mlat-server is slightly out of sync with mlat-client at the moment; you'll need to wait until I update the server code.

**Comment by Chrisoo** [comment]
OK thanks, so I'm waiting for code updates.

**Comment by Romeo-Golf** [comment]
Did this happen? :)
