### ISSUE TITLE
AttributeError: '_modes.Reader' object has no attribute 'modeac_filter'

### ISSUE THREAD

**Issue by marcus-aa** [mutability/mlat-client#22]
```
~# Wed Apr  5 04:23:17 2017 mlat-client 0.2.9 starting up
Traceback (most recent call last):
  File "/root/mlat-client/mlat-client", line 102, in <module>
    main()
  File "/root/mlat-client/mlat-client", line 81, in main
    mode=options.connection_mode(args))
  File "/root/mlat-client/mlat/client/receiver.py", line 62, in __init__
    self.reset_connection()
  File "/root/mlat-client/mlat/client/receiver.py", line 105, in reset_connection
    self.reader.modeac_filter = self.modeac_filter
AttributeError: '_modes.Reader' object has no attribute 'modeac_filter'

```

**Comment by mutability** [comment]
Sounds like you don't have the updated _modes extension module built/installed

**Comment by mutability** [comment]
https://github.com/mutability/mlat-client/blob/master/modes_reader.c#L91

**Comment by marcus-aa** [comment]
Solved by using setup.py installation, had only done dkpg.
