### ISSUE TITLE
Failed to run with: `ModuleNotFoundError: No module named 'asyncore'`

### ISSUE THREAD

**Issue by assapir** [mutability/mlat-client#39]
```
python --version
Python 3.12.3
```
```shell
> fa-mlat-client
Traceback (most recent call last):
  File "/usr/bin/fa-mlat-client", line 5, in <module>
    from flightaware.client.cli import main
  File "/usr/lib/python3.12/site-packages/flightaware/client/cli.py", line 8, in <module>
    from flightaware.client.adeptclient import AdeptConnection, UdpServerConnection
  File "/usr/lib/python3.12/site-packages/flightaware/client/adeptclient.py", line 7, in <module>
    import asyncore
ModuleNotFoundError: No module named 'asyncore'
```

**Comment by abcd567a** [comment]
fa-mlat-client gives following runtime error:
ModuleNotFoundError: No module named ‘asyncore’

[asyncore](https://docs.python.org/3.11/library/asyncore.html#module-asyncore) — Asynchronous socket handler
**Deprecated** since version 3.6, **will be removed in version 3.12**: </br>The [asyncore](https://docs.python.org/3.11/library/asyncore.html#module-asyncore) module is deprecated (see [PEP 594](https://peps.python.org/pep-0594/#asyncore) for details). Please use [asyncio](https://docs.python.org/3.11/library/asyncio.html#module-asyncio) instead.
